// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ExtractData, ExtractErrors, ExtractResponses, FetchData, FetchErrors, FetchResponses, RawFetchData, RawFetchErrors, RawFetchResponses, RawSearchData, RawSearchErrors, RawSearchResponses, SearchData, SearchErrors, SearchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Fetch a URL and return an AI-synthesized answer based on page content and your prompt.
 */
export const fetch = <ThrowOnError extends boolean = false>(options?: Options<FetchData, ThrowOnError>) => (options?.client ?? client).post<FetchResponses, FetchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Search the web and return an AI-synthesized answer from the retrieved results.
 */
export const search = <ThrowOnError extends boolean = false>(options?: Options<SearchData, ThrowOnError>) => (options?.client ?? client).post<SearchResponses, SearchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Fetch a URL and return raw markdown or HTML.
 */
export const rawFetch = <ThrowOnError extends boolean = false>(options?: Options<RawFetchData, ThrowOnError>) => (options?.client ?? client).post<RawFetchResponses, RawFetchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/raw_fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Run web search and return raw results.
 */
export const rawSearch = <ThrowOnError extends boolean = false>(options?: Options<RawSearchData, ThrowOnError>) => (options?.client ?? client).post<RawSearchResponses, RawSearchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/raw_search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Fetch a URL and return chunks relevant to a query.
 */
export const extract = <ThrowOnError extends boolean = false>(options?: Options<ExtractData, ThrowOnError>) => (options?.client ?? client).post<ExtractResponses, ExtractErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/extract',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
