// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PostV1ExtractData, PostV1ExtractErrors, PostV1ExtractResponses, PostV1FetchData, PostV1FetchErrors, PostV1FetchResponses, PostV1RawFetchData, PostV1RawFetchErrors, PostV1RawFetchResponses, PostV1RawSearchData, PostV1RawSearchErrors, PostV1RawSearchResponses, PostV1SearchData, PostV1SearchErrors, PostV1SearchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Fetch a URL and return an AI-synthesized answer based on page content and your prompt.
 */
export const postV1Fetch = <ThrowOnError extends boolean = false>(options?: Options<PostV1FetchData, ThrowOnError>) => (options?.client ?? client).post<PostV1FetchResponses, PostV1FetchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Search the web and return an AI-synthesized answer from the retrieved results.
 */
export const postV1Search = <ThrowOnError extends boolean = false>(options?: Options<PostV1SearchData, ThrowOnError>) => (options?.client ?? client).post<PostV1SearchResponses, PostV1SearchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Fetch a URL and return raw markdown or HTML.
 */
export const postV1RawFetch = <ThrowOnError extends boolean = false>(options?: Options<PostV1RawFetchData, ThrowOnError>) => (options?.client ?? client).post<PostV1RawFetchResponses, PostV1RawFetchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/raw_fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Run web search and return raw results.
 */
export const postV1RawSearch = <ThrowOnError extends boolean = false>(options?: Options<PostV1RawSearchData, ThrowOnError>) => (options?.client ?? client).post<PostV1RawSearchResponses, PostV1RawSearchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/raw_search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Fetch a URL and return chunks relevant to a query.
 */
export const postV1Extract = <ThrowOnError extends boolean = false>(options?: Options<PostV1ExtractData, ThrowOnError>) => (options?.client ?? client).post<PostV1ExtractResponses, PostV1ExtractErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/extract',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
