// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.quercle.dev' | (string & {});
};

export type PostV1FetchData = {
    body?: {
        /**
         * The URL to fetch and analyze.
         */
        url: string;
        /**
         * Instructions for how to analyze the page content. Be specific about what information you want to extract.
         */
        prompt: string;
    };
    path?: never;
    query?: never;
    url: '/v1/fetch';
};

export type PostV1FetchErrors = {
    /**
     * Bad request - invalid URL, prompt, or request format
     */
    400: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Unauthorized - missing or invalid API key
     */
    401: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Payment required - insufficient credits
     */
    402: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Too many requests - rate limit exceeded
     */
    429: {
        /**
         * Rate limit error details.
         */
        detail: string;
        /**
         * Additional validation or error context.
         */
        errors?: Array<unknown>;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
};

export type PostV1FetchError = PostV1FetchErrors[keyof PostV1FetchErrors];

export type PostV1FetchResponses = {
    /**
     * Fetch completed.
     */
    200: {
        /**
         * AI-synthesized answer based on the fetched page and your prompt.
         */
        result: string;
    };
};

export type PostV1FetchResponse = PostV1FetchResponses[keyof PostV1FetchResponses];

export type PostV1SearchData = {
    body?: {
        /**
         * The search query to find information about. Be specific.
         */
        query: string;
        /**
         * Only include results from these domains (e.g., ['example.com', 'docs.example.org']).
         */
        allowed_domains?: Array<string>;
        /**
         * Exclude results from these domains (e.g., ['example.com', 'docs.example.org']).
         */
        blocked_domains?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/v1/search';
};

export type PostV1SearchErrors = {
    /**
     * Bad request - invalid query or domain format
     */
    400: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Unauthorized - missing or invalid API key
     */
    401: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Payment required - insufficient credits
     */
    402: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Too many requests - rate limit exceeded
     */
    429: {
        /**
         * Rate limit error details.
         */
        detail: string;
        /**
         * Additional validation or error context.
         */
        errors?: Array<unknown>;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
};

export type PostV1SearchError = PostV1SearchErrors[keyof PostV1SearchErrors];

export type PostV1SearchResponses = {
    /**
     * Search completed.
     */
    200: {
        /**
         * AI-synthesized answer based on web search results.
         */
        result: string;
    };
};

export type PostV1SearchResponse = PostV1SearchResponses[keyof PostV1SearchResponses];

export type PostV1RawFetchData = {
    body?: {
        /**
         * The URL to fetch.
         */
        url: string;
        /**
         * Output format for fetched content. Defaults to `markdown`.
         */
        format?: 'markdown' | 'html';
        /**
         * Enable prompt-injection detection when `format` is `markdown`.
         */
        use_safeguard?: boolean;
    };
    path?: never;
    query?: never;
    url: '/v1/raw_fetch';
};

export type PostV1RawFetchErrors = {
    /**
     * Bad request - invalid URL, format, or request payload
     */
    400: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Unauthorized - missing or invalid API key
     */
    401: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Payment required - insufficient credits
     */
    402: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Too many requests - rate limit exceeded
     */
    429: {
        /**
         * Rate limit error details.
         */
        detail: string;
        /**
         * Additional validation or error context.
         */
        errors?: Array<unknown>;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
};

export type PostV1RawFetchError = PostV1RawFetchErrors[keyof PostV1RawFetchErrors];

export type PostV1RawFetchResponses = {
    /**
     * Raw fetch completed.
     */
    200: {
        /**
         * Fetched content.
         */
        result: string;
        /**
         * True when safeguard marks content as unsafe.
         */
        unsafe?: boolean;
    };
};

export type PostV1RawFetchResponse = PostV1RawFetchResponses[keyof PostV1RawFetchResponses];

export type PostV1RawSearchData = {
    body?: {
        /**
         * The search query to run against the web.
         */
        query: string;
        /**
         * Output format for search results. Defaults to `markdown`.
         */
        format?: 'markdown' | 'json';
        /**
         * Enable prompt-injection detection on search results.
         */
        use_safeguard?: boolean;
    };
    path?: never;
    query?: never;
    url: '/v1/raw_search';
};

export type PostV1RawSearchErrors = {
    /**
     * Bad request - invalid query, format, or request payload
     */
    400: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Unauthorized - missing or invalid API key
     */
    401: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Payment required - insufficient credits
     */
    402: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Too many requests - rate limit exceeded
     */
    429: {
        /**
         * Rate limit error details.
         */
        detail: string;
        /**
         * Additional validation or error context.
         */
        errors?: Array<unknown>;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
};

export type PostV1RawSearchError = PostV1RawSearchErrors[keyof PostV1RawSearchErrors];

export type PostV1RawSearchResponses = {
    /**
     * Raw search completed.
     */
    200: {
        /**
         * Search results markdown (`format=markdown`).
         */
        result: string;
        /**
         * True when safeguard marks content as unsafe.
         */
        unsafe?: boolean;
    } | {
        /**
         * Search results list (`format=json`).
         */
        result: Array<{
            /**
             * Search result title.
             */
            title: string;
            /**
             * Search result URL.
             */
            url: string;
            /**
             * Search result snippet text.
             */
            content: string;
        }>;
        /**
         * True when safeguard marks content as unsafe.
         */
        unsafe?: boolean;
    };
};

export type PostV1RawSearchResponse = PostV1RawSearchResponses[keyof PostV1RawSearchResponses];

export type PostV1ExtractData = {
    body?: {
        /**
         * The URL to fetch and extract relevant chunks from.
         */
        url: string;
        /**
         * What information to extract from the page content.
         */
        query: string;
        /**
         * Output format for extracted chunks. Defaults to `markdown`.
         */
        format?: 'markdown' | 'json';
        /**
         * Enable prompt-injection detection on selected extracted content.
         */
        use_safeguard?: boolean;
    };
    path?: never;
    query?: never;
    url: '/v1/extract';
};

export type PostV1ExtractErrors = {
    /**
     * Bad request - invalid URL, query, format, or request payload
     */
    400: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Unauthorized - missing or invalid API key
     */
    401: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Payment required - insufficient credits
     */
    402: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
    /**
     * Too many requests - rate limit exceeded
     */
    429: {
        /**
         * Rate limit error details.
         */
        detail: string;
        /**
         * Additional validation or error context.
         */
        errors?: Array<unknown>;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Human-readable error message.
         */
        detail: string;
    };
};

export type PostV1ExtractError = PostV1ExtractErrors[keyof PostV1ExtractErrors];

export type PostV1ExtractResponses = {
    /**
     * Extract completed.
     */
    200: {
        /**
         * Relevant chunks markdown (`format=markdown`).
         */
        result: string;
        /**
         * True when safeguard marks content as unsafe.
         */
        unsafe?: boolean;
    } | {
        /**
         * Relevant chunks array (`format=json`).
         */
        result: Array<string>;
        /**
         * True when safeguard marks content as unsafe.
         */
        unsafe?: boolean;
    };
};

export type PostV1ExtractResponse = PostV1ExtractResponses[keyof PostV1ExtractResponses];
